version: '3.8'

services:
  govassist:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_URL=http://ollama:11434  # <-- Add this
    depends_on:
      - postgres
      - ollama  # <-- Ensure ollama starts before govassist

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: govassist
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama  # optional: persist model cache

volumes:
  pgdata:
  ollama-data:
